name: "Poppins"
version: "v22"
filename: "Poppins"
group: "Sans Serif"
cssFile: "resource://Carbon.Webfonts/Poppins/Style.css"
fontWeight:
  - 100
  - 200
  - 300
  - 400
  - 500
  - 600
  - 700
  - 800
  - 900
